sudo: false

language: c

os:
  - linux
  - osx

cache:
  directories:
    - nim

env:
  global:
    - NIMREPO="https://github.com/nim-lang/Nim"
    - NIMVER="$(git ls-remote ${NIMREPO} devel | cut -f 1)"
    # - NIMVER="eaca5be9d6e205e8aa7055306122a6c053ef35a6" # hard-code the version for now -- Thu Oct 18 17:23:34 EDT 2018 - kmodi
    - NIMDIR="${TRAVIS_BUILD_DIR}/nim/${NIMVER}"

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libsdl1.2-dev
    - libgc-dev
    - libsfml-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install boehmgc; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sfml; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gnu-tar; fi
  - set -e
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then unset -f cd; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then shell_session_update() { :; }; fi

install:
  - echo "NIMDIR = ${NIMDIR}"
  # After building nim, wipe csources to save on cache space.
  - "{ [ -f ${NIMDIR}/bin/nim ]; } ||
      ( rm -rf nim;
        mkdir -p nim;
        git clone --single-branch --branch devel --depth=1 ${NIMREPO} ${NIMDIR};
        cd ${NIMDIR};
        [ -d csources ] || git clone --depth 1 https://github.com/nim-lang/csources.git;
        cd csources;
        echo '[phase 0] Building csources';
        sh build.sh;
        cd ..;
        echo '[phase 1] Building koch';
        ./bin/nim c koch;
        echo '[phase 2] Building nim';
        ./koch boot -d:release;
        export PATH=\"${NIMDIR}/bin:${PATH}\";
        [ $TRAVIS_OS_NAME == \"osx\" ] || echo '[phase 3] Running koch doc0';
        [ $TRAVIS_OS_NAME == \"osx\" ] || ./koch doc0;
        [ $TRAVIS_OS_NAME == \"osx\" ] || echo '[phase 4] Running koch csource';
        [ $TRAVIS_OS_NAME == \"osx\" ] || ./koch csource -d:release;
        [ $TRAVIS_OS_NAME == \"osx\" ] || echo '[phase 5] Running koch xz';
        [ $TRAVIS_OS_NAME == \"osx\" ] || ./koch xz -d:release;
        rm -rf csources;
      )"
  - export PATH="${NIMDIR}/bin:${PATH}" # Need to set PATH in the case cached nim build is used

script:
  - echo '[In script block]'
  - nim --version

before_deploy:
  - cd "${TRAVIS_BUILD_DIR}"
  - export DEPLOY_VERSION="$(nim --version | grep -Po 'Version \K[0-9.]+')"
  - export ASSETFILE="nim-${DEPLOY_VERSION}.tar.xz"
  - cp -f "${NIMDIR}/build/${ASSETFILE}" "${ASSETFILE}"
  - echo '[phase n-1] The deploy will start now ..'

deploy:
  provider: releases
  api_key: "${GITHUB_OAUTH_TOKEN}"
  file: "${ASSETFILE}"
  skip_cleanup: true
  on:
    os: linux                   # Deploy only on linux
    tags: false

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
