sudo: false

language: c

os:
  - linux
  - osx

cache:
  directories:
    - nim

env:
  global:
    - NIMREPO="https://github.com/nim-lang/Nim"
    - NIMVER="$(git ls-remote ${NIMREPO} devel | cut -f 1)"
    - NIMDIR="${TRAVIS_BUILD_DIR}/nim/${NIMVER}"
    - DATESTR="$(date +'%Y-%m-%d')"
    - DO_DEPLOY=no

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libsdl1.2-dev
    - libgc-dev
    - libsfml-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install boehmgc; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sfml; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gnu-tar; fi
  - set -e
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then unset -f cd; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then shell_session_update() { :; }; fi

install:
  - echo "NIMDIR = ${NIMDIR}"
  # After building nim, wipe csources to save on cache space.
  - "{ [ -f ${NIMDIR}/bin/nim ]; } ||
      ( rm -rf nim;
        mkdir -p nim;
        git clone --single-branch --branch devel --depth=1 ${NIMREPO} ${NIMDIR};
        cd ${NIMDIR};
        export NIMVERSHORT=$(git log --format=%h -1);
        [ -d csources ] || git clone --depth 1 https://github.com/nim-lang/csources.git;
        cd csources;
        echo '[phase 0] Building csources';
        sh build.sh;
        cd ..;
        echo '[phase 1] Building koch';
        ./bin/nim c koch;
        echo '[phase 2] Building nim';
        ./koch boot -d:release;
        export PATH=\"${NIMDIR}/bin:${PATH}\";
        echo '[phase 3] Running koch doc0';
        ./koch doc0;
        echo '[phase 4] Running koch csource';
        ./koch csource -d:release;
        echo '[phase 5] Running koch xz';
        ./koch xz -d:release;
        echo '[phase 6] Running koch testinstall';
        ./koch testinstall;
        rm -rf csources;
        export DO_DEPLOY=yes;
      )"
  - export PATH="${NIMDIR}/bin:${PATH}" # Need to set PATH in the case cached nim build is used

script:
  - echo '[In script block]'
  - nim --version

before_deploy:
  - cd "${TRAVIS_BUILD_DIR}"
  - export DEPLOY_VERSION="$(nim --version | head -n 1 | perl -pe 's/.*Version ([0-9.]+).*/\1/')"
  - export ASSETFILE="nim-${DEPLOY_VERSION}-${TRAVIS_OS_NAME}.tar.xz"
  - cp -f "${NIMDIR}/build/nim-${DEPLOY_VERSION}.tar.xz" "${ASSETFILE}"
  # Set up git user name and tag this commit
  # https://docs.travis-ci.com/user/deployment/releases/
  # Set the GIT_TAG_USER_NAME and GIT_TAG_USER_EMAIL env var variables
  # in Travis CI setup for this repo.
  - git config --local user.name "${GIT_TAG_USER_NAME}"
  - git config --local user.email "${GIT_TAG_USER_EMAIL}"
  - git tag "nb-${DATESTR}-${NIMVERSHORT}" # nb - nightly build
  - echo '[phase n-1] The deploy will start now ..'

deploy:
  provider: releases
  api_key: "${GITHUB_OAUTH_TOKEN}"
  file: "${ASSETFILE}"
  name: "Nightly build ${DATESTR} ${NIMVERSHORT}"
  body: "This nightly release is built using https://github.com/nim-lang/Nim/tree/${NIMVER}"
  skip_cleanup: true
  on:
    condition: $DO_DEPLOY = yes
    tags: true

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
