sudo: false

language: c

# os:
#   - linux
#   - osx

# matrix:
#   allow_failures:
#     - os: linux

cache:
  directories:
    - nim

env:
  global:
    - NIMREPO="https://github.com/nim-lang/Nim"
    - NIMVER="$(git ls-remote ${NIMREPO} devel | cut -f 1)"
    - NIMDIR="${TRAVIS_BUILD_DIR}/nim/${NIMVER}"
    - USE_CACHE=1

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libsdl1.2-dev
    - libgc-dev
    - libsfml-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install boehmgc; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sfml; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gnu-tar; fi
  - set -e
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then unset -f cd; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then shell_session_update() { :; }; fi

install:
  - echo "NIMDIR = ${NIMDIR}"
  # After building nim, wipe csources to save on cache space.
  - "{ [ ${USE_CACHE} -eq 1 ] || [ -f ${NIMDIR}/bin/nim ]; } ||
      ( rm -rf nim;
        mkdir -p nim;
        git clone --single-branch --branch devel --depth=1 ${NIMREPO} ${NIMDIR};
        cd ${NIMDIR};
        [ -d csources ] || git clone --depth 1 https://github.com/nim-lang/csources.git;
        cd csources;
        echo '[phase 0] Building csources';
        sh build.sh;
        cd ..;
        echo '[phase 1] Building koch';
        ./bin/nim c koch;
        echo '[phase 2] Building nim';
        ./koch boot -d:release;
        export PATH=\"${NIMDIR}/bin:${PATH}\";
        echo '[phase 3] Running koch doc0';
        ./koch doc0;
        echo '[phase 4] Running koch csource';
        ./koch csource -d:release;
        rm -rf csources;
      )"
  - export PATH="${NIMDIR}/bin:${PATH}" # Need to set PATH in the case cached nim build is used
  # Restore the .travis.yml deleted from cache
  - git clone --single-branch --branch devel --depth=1 ${NIMREPO} temp && cp temp/.travis.yml ${NIMDIR}/.

script:
  - echo '[In script block]'
  - nim --version

before_deploy:
  - echo '[In before_deploy block]'
  - cd "${NIMDIR}"
  - echo '[phase n-2] Running koch xz'
  # Create the release archive.
  - ./koch xz -d:release
  - rm ./.travis.yml # so that Travis deploy is not confused by the Nim repo .travis.yml
  - echo '[phase n-1] The deploy will start now ..'

deploy:
  provider: releases
  api_key: "${GITHUB_OAUTH_TOKEN}"
  file: "nim/${NIMVER}/build/nim-*.tar.xz"
  file_glob: true
  skip_cleanup: true
  on:
    tags: false

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
